openapi: 3.0.0
info:
  title: OZmap Test API
  description: API documentation for OZmap technical test.
  version: 1.0.0
externalDocs:
  description: API Repository on Github
  url: https://github.com/LucasXXI/OZmaptest
contact:
  name: Fale comigo
  email: lucasleal2001@gmail.com
  url: github.com/lucasxxi
servers:
  - url: http://localhost:3000
    description: API test server
paths:
  /users:
    get:
      tags:
        - Default
      summary: fetch all users in database
      responses:
        '200':
          description: Sucesso
          content:
            aplication/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    age:
                      type: integer
                    email:
                      type: string
        '400':
          description: bad request!
    post:
      tags: 
        - Post user
      summary: post a user in the database
      description: This route creates a user and store on the database
      requestBody:
        required: true
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/user'
      responses: 
        "200": 
          description: OK, user Created in the database
        "400":
          description: Bad Request!



components:
  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/user'
  schemas:
    user:
      type: object
      properties:
        name:
          type: string
        age: 
          type: integer
        email:
          type: string

                
                
                
                